version: "3.10"
services:
  worker:
    build: .
    environment:
      SESSION_NAME: $SESSION_NAME
      API_ID: $API_ID
      API_HASH: $API_HASH
      MONGODB_URL: $MONGODB_URL
      BOT_TOKEN : $BOT_TOKEN
